### ISSUE TITLE
current installation method

### ISSUE THREAD

**Issue by raddessi** [a10networks/a10-saltstack#16]
Hi, it seems you may be changing the layout of the repo, what is the current installation method I can use?

**Comment by hthompson6** [comment]
Yes it's gone through a few major reworks in preparation for introduction into Saltstack's core repository. In the mean time, I'll update the readme to reflect the new installation process by end of day tomorrow.

**Comment by raddessi** [comment]
Awesome! No rush though really. I've been tracking this for a while, I can't wait to get it working with our systems. Thanks for the work!

**Comment by raddessi** [comment]
Is this still being developed? If so, are there plans to get the a10 modules separated out to their own formula or to push them upstream in to the salt repo itself? I don't want to run from a10networks salt repo

**Comment by hthompson6** [comment]
Apologies for the late response. Development was temporarily halted in favor of work on Ansible.

We had separated out everything already and prepped a PR for the upstream repo; however, there is still some work left to do on this repo (since the upstream one will import this).

Our Ansible repositories are stabilizing. Once we've accomplished this, more work will be done on this repository.

If you wish, you may reach out to support@a10networks.com and cc myself: hthompson@a10networks.com for further discussion.
